<?php
/**
 * Created by PhpStorm.
 * User: vin-d
 * Date: 20/03/2019
 * Time: 12:29
 */

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

class SortiesRepository extends EntityRepository {
    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

}